### ISSUE TITLE
缺少依赖包jeewx-boot-start-cor

### ISSUE THREAD

**Issue by Neil-Zhou** [jeecgboot/jeewx-boot#14]
##### 问题描述：
Failure to find org.jeewxframework.boot:jeewx-boot-start-core:pom:1.0.5 in http://maven.aliyun.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nexus-aliyun has elapsed or updates are forced

**Comment by zhangdaiscott** [comment]
http://doc.jeewx.com/1275614
