### ISSUE TITLE
微信公众号文章图片上传出错

### ISSUE THREAD

**Issue by ReExia** [jeecgboot/jeewx-boot#16]
##### 问题描述：

微信公众号文章图片上传出错
oss.imgDomain 怎么配置，配成公网也不行

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/70389584-772b4980-19fc-11ea-8d10-857ca142eb82.png)

http://doc.jeewx.com/1414959
