### ISSUE TITLE
部署成jar包后，无法执行

### ISSUE THREAD

**Issue by batigol6655** [jeecgboot/jeewx-boot#3]
java -jar 运行时提示：没有主清单属性

**Comment by zhangdaiscott** [comment]
system pom加这个了吗
http://jeewx-boot.mydoc.io/?t=346355


![image](https://user-images.githubusercontent.com/3162115/61605122-a8d28c80-ac76-11e9-9dcb-1d37b0f0350d.png)

**Comment by batigol6655** [comment]
加了，代码下载下来后就有这段


2019-07-22 

fanzl1983 



发件人：scott <notifications@github.com>
发送时间：2019-07-22 11:47
主题：Re: [zhangdaiscott/jeewx-boot] 部署成jar包后，无法执行 (#3)
收件人："zhangdaiscott/jeewx-boot"<jeewx-boot@noreply.github.com>
抄送："batigol6655"<fanzl1983@163.com>,"Author"<author@noreply.github.com>

system pom加这个了吗



org.springframework.boot
spring-boot-maven-plugin

**Comment by zhangdaiscott** [comment]
参考这个配置
https://www.jianshu.com/p/f39904dafbdd

**Comment by batigol6655** [comment]
加上这段代码确实可以了
