### ISSUE TITLE
部署成功，并且运行成功后，出现乱码问题

### ISSUE THREAD

**Issue by batigol6655** [jeecgboot/jeewx-boot#4]
所有项目编码集为utf-8,数据库字符集为utf-8,但是在页面修改数据，保存后，存到数据库中的数据是乱码

**Comment by a357730572** [comment]
我也遇到同样的问题，公众号名称那里一修改就是乱码。
而且修改公众号信息，后台报错。提示找不到weixin_group_message_send_log这个表，我查看了一下，sql里没有这个表的定义，wx项目下也没有对应的实体类。但是修改公众号信息，就会报错。
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'jeewx-boot-201907.weixin_group_message_send_log' doesn't exist

**Comment by batigol6655** [comment]
> 我也遇到同样的问题，公众号名称那里一修改就是乱码。
> 而且修改公众号信息，后台报错。提示找不到weixin_group_message_send_log这个表，我查看了一下，sql里没有这个表的定义，wx项目下也没有对应的实体类。但是修改公众号信息，就会报错。
> Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'jeewx-boot-201907.weixin_group_message_send_log' doesn't exist

我和你同样的问题，希望帮忙解决一下，或者提醒在哪修改，谢谢

**Comment by batigol6655** [comment]
> 我也遇到同样的问题，公众号名称那里一修改就是乱码。
> 而且修改公众号信息，后台报错。提示找不到weixin_group_message_send_log这个表，我查看了一下，sql里没有这个表的定义，wx项目下也没有对应的实体类。但是修改公众号信息，就会报错。
> Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'jeewx-boot-201907.weixin_group_message_send_log' doesn't exist

乱码问题解决了，代码里的数据库连接部分的编码集和提供的sql文件编码集不一致，修改如下
 url: jdbc:mysql://127.0.0.1:3306/jeewxboot?useUnicode=true&characterEncoding=utf-8&useSSL=true
然后数据库使用utf8

**Comment by a357730572** [comment]
> > 我也遇到同样的问题，公众号名称那里一修改就是乱码。
> > 而且修改公众号信息，后台报错。提示找不到weixin_group_message_send_log这个表，我查看了一下，sql里没有这个表的定义，wx项目下也没有对应的实体类。但是修改公众号信息，就会报错。
> > Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'jeewx-boot-201907.weixin_group_message_send_log' doesn't exist
> 
> 乱码问题解决了，代码里的数据库连接部分的编码集和提供的sql文件编码集不一致，修改如下
> url: jdbc:mysql://127.0.0.1:3306/jeewxboot?useUnicode=true&characterEncoding=utf-8&useSSL=true
> 然后数据库使用utf8

好的，我试一下。公众号地址那里你配置成功了吗？我那里现在也不通。

**Comment by zhangdaiscott** [comment]
那个代码提示提示找不到weixin_group_message_send_log？

**Comment by a357730572** [comment]
> 那个代码提示提示找不到weixin_group_message_send_log？

是的

**Comment by zhangdaiscott** [comment]
是那块代码？ 截图看看，报的具体错误

**Comment by a357730572** [comment]
> 是那块代码？ 截图看看，报的具体错误

我可以加你qq好友  发给你吗?

**Comment by zhangdaiscott** [comment]
执行下这段sql就好了


-- ----------------------------
-- Table structure for weixin_huodong_biz_jwid
-- ----------------------------
DROP TABLE IF EXISTS `weixin_huodong_biz_jwid`;
CREATE TABLE `weixin_huodong_biz_jwid` (
  `id` varchar(32) NOT NULL COMMENT '序号',
  `table_name` varchar(255) default NULL COMMENT '表名称',
  `table_remake` varchar(255) default NULL COMMENT '表注释',
  `table_type` varchar(2) default NULL COMMENT '表类型：''1''：微信，''2''：活动',
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='微信活动jwid表';

-- ----------------------------
-- Records of weixin_huodong_biz_jwid
-- ----------------------------
INSERT INTO `weixin_huodong_biz_jwid` VALUES ('ff80808152a2abd20153592394830017', 'weixin_texttemplate', '文本模板', '1');
INSERT INTO `weixin_huodong_biz_jwid` VALUES ('ff80808152a2abd20153592394830018', 'weixin_subscribe', '关注欢迎语', '1');
INSERT INTO `weixin_huodong_biz_jwid` VALUES ('ff80808152a2abd20153592394830019', 'weixin_newstemplate', '图文模板表', '1');
INSERT INTO `weixin_huodong_biz_jwid` VALUES ('ff80808152a2abd20153592394830020', 'weixin_menu', '微信菜单表', '1');
INSERT INTO `weixin_huodong_biz_jwid` VALUES ('ff80808152a2abd20153592394830021', 'weixin_gzuser', '粉丝表', '1');
INSERT INTO `weixin_huodong_biz_jwid` VALUES ('ff80808152a2abd20153592394830024', 'weixin_autoresponse_default', '未识别回复语', '1');
INSERT INTO `weixin_huodong_biz_jwid` VALUES ('ff80808152a2abd20153592394830025', 'weixin_autoresponse', '关键字表', '1');
INSERT INTO `weixin_huodong_biz_jwid` VALUES ('ff80808152a2abd20153592394830026', 'weixin_receivetext', '消息存储表', '1');
INSERT INTO `weixin_huodong_biz_jwid` VALUES ('ff80808152a2abd20153592394830028', 'weixin_newstemplate', '图文素材表', '1');
INSERT INTO `weixin_huodong_biz_jwid` VALUES ('ff80808152a2abd20153592394830051', 'weixin_tag', '粉丝标签表', '1');
