### ISSUE TITLE
出现中文乱码

### ISSUE THREAD

**Issue by JianLiangHe** [jeecgboot/jeewx-boot#6]
自定义菜单,选项中,还有其他功能,会出现中文乱码,如何解决?

**Comment by zhangdaiscott** [comment]
更新git代码，此问题已经修复

**Comment by JianLiangHe** [comment]
我下载项目,部署,还有此问题出现




------------------ 原始邮件 ------------------
发件人: "scott"<notifications@github.com>; 
发送时间: 2019年7月29日(星期一) 上午10:00
收件人: "zhangdaiscott/jeewx-boot"<jeewx-boot@noreply.github.com>; 
抄送: "user_hjl"<844131681@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zhangdaiscott/jeewx-boot] 出现中文乱码 (#6)




更新git代码，此问题已经修复

**Comment by JianLiangHe** [comment]
问题已解决




------------------ 原始邮件 ------------------
发件人: "scott"<notifications@github.com>; 
发送时间: 2019年7月29日(星期一) 上午10:00
收件人: "zhangdaiscott/jeewx-boot"<jeewx-boot@noreply.github.com>; 
抄送: "user_hjl"<844131681@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zhangdaiscott/jeewx-boot] 出现中文乱码 (#6)




Closed #6.
