### ISSUE TITLE
jar无法下载

### ISSUE THREAD

**Issue by wanghaoyu1989** [jeecgboot/jeewx-boot#9]
##### 问题描述：jeewx-boot-start-core-1.0.5 无法下载
1.maven setting 已经设置
2.maven下载jar已经切换为jeewx 私服，私服似乎无法打开

##### 问题截图：
![image](https://user-images.githubusercontent.com/19188616/63823744-7b6cb300-c987-11e9-8108-a1e1ff4b9b4b.png)
![image](https://user-images.githubusercontent.com/19188616/63823767-8a536580-c987-11e9-8340-e3c864f37f8f.png)

**Comment by zhangdaiscott** [comment]
今天仓库不稳定，再试试
